---
- name: Ensure destination for compose file exists
  ansible.builtin.file:
    path: "{{ docker_compose.generator.output_path }}"
    state: directory
    owner: "{{ docker_compose.generator.uid }}"
    group: "{{ docker_compose.generator.gid }}"
    mode: "{{ docker_compose.generator.directory_mode }}"

- name: Write docker compose file
  ansible.builtin.template:
    src: "{{ role_path }}/templates/docker-compose.yml.j2"
    dest: "{{ docker_compose.generator.output_path }}/docker-compose.yml"
    owner: "{{ docker_compose.generator.uid }}"
    group: "{{ docker_compose.generator.gid }}"
    mode: "{{ docker_compose.generator.file_mode }}"

- name: Write dorenv file
  ansible.builtin.template:
    src: "{{ role_path }}/templates/dotenv.j2"
    dest: "{{ docker_compose.generator.output_path }}/.env"
    owner: "{{ docker_compose.generator.uid }}"
    group: "{{ docker_compose.generator.gid }}"
    mode: "{{ docker_compose.generator.file_mode }}"
  when:
    - docker_compose.dotenv is defined
    - docker_compose.dotenv.keys()| length > 0
